// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types/person.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Location类型
// 枚举类型第一个字段必须为0
type LocationType int32

const (
	LocationType_CITY    LocationType = 0
	LocationType_COUNTRY LocationType = 1
	LocationType_ZIP     LocationType = 2
)

var LocationType_name = map[int32]string{
	0: "CITY",
	1: "COUNTRY",
	2: "ZIP",
}
var LocationType_value = map[string]int32{
	"CITY":    0,
	"COUNTRY": 1,
	"ZIP":     2,
}

func (x LocationType) String() string {
	return proto.EnumName(LocationType_name, int32(x))
}
func (LocationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_person_7b979b5563cdb61a, []int{0}
}

// Location
type Location struct {
	Type                 LocationType `protobuf:"varint,1,opt,name=type,proto3,enum=types.LocationType" json:"type,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_person_7b979b5563cdb61a, []int{0}
}
func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (dst *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(dst, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetType() LocationType {
	if m != nil {
		return m.Type
	}
	return LocationType_CITY
}

func (m *Location) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 人
type Person struct {
	// 后面的数字表示标识号
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age  int32  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	// repeated表示可重复
	// 可以有多个Location
	Locations            []*Location `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_person_7b979b5563cdb61a, []int{1}
}
func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (dst *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(dst, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetLocations() []*Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

func init() {
	proto.RegisterType((*Location)(nil), "types.Location")
	proto.RegisterType((*Person)(nil), "types.Person")
	proto.RegisterEnum("types.LocationType", LocationType_name, LocationType_value)
}

func init() { proto.RegisterFile("types/person.proto", fileDescriptor_person_7b979b5563cdb61a) }

var fileDescriptor_person_7b979b5563cdb61a = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0xa9, 0x2c, 0x48,
	0x2d, 0xd6, 0x2f, 0x48, 0x2d, 0x2a, 0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x05, 0x8b, 0x29, 0xb9, 0x73, 0x71, 0xf8, 0xe4, 0x27, 0x27, 0x96, 0x64, 0xe6, 0xe7, 0x09, 0xa9,
	0x73, 0xb1, 0x80, 0x04, 0x25, 0x18, 0x15, 0x18, 0x35, 0xf8, 0x8c, 0x84, 0xf5, 0xc0, 0x2a, 0xf4,
	0x60, 0xd2, 0x21, 0x95, 0x05, 0xa9, 0x41, 0x60, 0x05, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9,
	0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x52, 0x2c, 0x17, 0x5b, 0x00, 0xd8,
	0x7c, 0xb8, 0x2c, 0x23, 0x42, 0x56, 0x48, 0x80, 0x8b, 0x39, 0x31, 0x1d, 0xa2, 0x81, 0x35, 0x08,
	0xc4, 0x14, 0xd2, 0xe5, 0xe2, 0xcc, 0x81, 0x9a, 0x5c, 0x2c, 0xc1, 0xac, 0xc0, 0xac, 0xc1, 0x6d,
	0xc4, 0x8f, 0x66, 0x63, 0x10, 0x42, 0x85, 0x96, 0x1e, 0x17, 0x0f, 0xb2, 0x43, 0x84, 0x38, 0xb8,
	0x58, 0x9c, 0x3d, 0x43, 0x22, 0x05, 0x18, 0x84, 0xb8, 0xb9, 0xd8, 0x9d, 0xfd, 0x43, 0xfd, 0x42,
	0x82, 0x22, 0x05, 0x18, 0x85, 0xd8, 0xb9, 0x98, 0xa3, 0x3c, 0x03, 0x04, 0x98, 0x92, 0xd8, 0xc0,
	0xbe, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x55, 0xb1, 0x40, 0x1d, 0xfb, 0x00, 0x00, 0x00,
}
